import type { Project } from "../_types/project";

export const PROJECTS: Project[] = [
  {
    id: 1,
    slug: "seo-portfolio-platform",
    title: "SEO-Friendly Personal Portfolio Platform",
    summary:
      "A fast, SEO-optimized software developer portfolio built with Next.js 16 and .NET Web API.",
    featured: true,
    year: 2026,
    role: "Full-stack Developer",
    stack: ["Next.js 16", "React", ".NET Web API", "MS SQL Server", "Tailwind"],
    tags: ["Portfolio", "SEO", "Next.js"],
    problem:
      "Traditional portfolios lacked SEO-friendly project pages and smooth project navigation.",
    solution:
      "Implemented App Router, intercepting routes, and modal project details with SEO-friendly full pages.",
    result:
      "Achieved Lighthouse SEO scores above 95 and improved project exploration UX.",
    features: [
      "Intercept modal + full page architecture",
      "Dynamic metadata and sitemap",
      "Filtering and search",
      "Reusable case study layout",
    ],
    images: ["/images/projects/portfolio-1.jpg", "/images/projects/portfolio-2.png"],
    links: {
      live: "https://example.com",
      github: "https://github.com/username/portfolio",
    },
  },
  {
    id: 2,
    slug: "nextjs-ecommerce-platform",
    title: "Next.js eCommerce Platform",
    summary:
      "A scalable eCommerce platform with server-side rendering and secure payments.",
    featured: true,
    year: 2025,
    role: "Full-stack Developer",
    stack: ["Next.js", ".NET Web API", "MS SQL Server", "Stripe"],
    tags: ["Ecommerce", "Next.js"],
    problem: "Slow page loads and low conversion rates on a legacy eCommerce site.",
    solution: "Built an SSR-based frontend with optimized API endpoints and Stripe integration.",
    result: "Page load time reduced by 40% and conversion rate increased.",
    features: ["SSR product pages", "Stripe payments", "Admin product management"],
    images: ["/images/projects/ecommerce-1.jpg"],
    links: {
       live: "https://example.com",
      github: "https://github.com/username/ecommerce"
    },
  },
  {
    id: 3,
    slug: "inventory-management-api",
    title: "Inventory Management API",
    summary: "A RESTful API for managing inventory and stock movements.",
    featured: false,
    year: 2025,
    role: "Backend Developer",
    stack: [".NET Web API", "MS SQL Server"],
    tags: ["API", ".NET"],
    problem: "Manual inventory tracking caused data inconsistency.",
    solution: "Designed normalized SQL tables and a RESTful API with validation.",
    result: "Improved inventory accuracy and reduced processing time.",
    features: ["CRUD endpoints", "Role-based access", "Structured logging"],
    images: ["/images/projects/inventory-1.jpg"],
    links: { github: "https://github.com/username/inventory-api" },
  },
  {
    id: 4,
    slug: "seo-optimization-dashboard",
    title: "SEO Optimization Dashboard",
    summary: "A dashboard to analyze and improve on-page SEO performance.",
    featured: false,
    year: 2024,
    role: "Full-stack Developer",
    stack: ["Next.js", ".NET Web API"],
    tags: ["SEO", "Dashboard"],
    problem: "Website owners lacked actionable SEO insights.",
    solution: "Built a dashboard that audits pages and provides SEO recommendations.",
    result: "Organic traffic increased by 35%.",
    features: ["SEO audits", "Keyword analysis", "Performance scoring"],
    images: ["/images/projects/seo-1.jpg"],
    links: {},
  },
  {
    id: 5,
    slug: "content-management-system",
    title: "Content Management System",
    summary: "A lightweight CMS for managing pages and blog content.",
    featured: false,
    year: 2024,
    role: "Full-stack Developer",
    stack: ["Next.js", ".NET Web API", "MS SQL Server"],
    tags: ["CMS", "Next.js"],
    problem: "Content updates required developer involvement.",
    solution: "Created a CMS with role-based access and live previews.",
    result: "Non-technical users could manage content independently.",
    features: ["Role-based permissions", "Draft & publish workflow", "Live preview"],
    images: ["/images/projects/cms-1.jpg"],
    links: {},
  },
  {
    id: 6,
    slug: "authentication-service",
    title: "Authentication & Authorization Service",
    summary: "Centralized authentication service using JWT.",
    featured: false,
    year: 2024,
    role: "Backend Developer",
    stack: [".NET Web API", "JWT", "MS SQL Server"],
    tags: ["Security", "API"],
    problem: "Multiple apps needed consistent authentication logic.",
    solution: "Implemented JWT authentication with refresh tokens.",
    result: "Improved security and reduced duplicated code.",
    features: ["JWT auth", "Refresh tokens", "User roles"],
    images: ["/images/projects/auth-1.jpg"],
    links: {},
  },
  {
    id: 7,
    slug: "performance-monitoring-dashboard",
    title: "Performance Monitoring Dashboard",
    summary: "Dashboard for tracking application performance metrics.",
    featured: false,
    year: 2023,
    role: "Full-stack Developer",
    stack: ["Next.js", ".NET Web API"],
    tags: ["Performance", "Monitoring"],
    problem: "Lack of visibility into system performance.",
    solution: "Built dashboards with metrics and alerts.",
    result: "Reduced incident response time.",
    features: ["Real-time metrics", "Alerts", "Historical data"],
    images: ["/images/projects/performance-1.jpg"],
    links: {},
  },
  {
    id: 8,
    slug: "web-scraper-api",
    title: "Web Scraper API",
    summary: "API service for scraping and aggregating web data.",
    featured: false,
    year: 2023,
    role: "Backend Developer",
    stack: [".NET Web API"],
    tags: ["Scraping", "API"],
    problem: "Manual data collection was time-consuming.",
    solution: "Automated scraping with scheduled jobs.",
    result: "Data collection time significantly reduced.",
    features: ["Scheduled scraping", "Data normalization"],
    images: ["/images/projects/scraper-1.jpg"],
    links: {},
  },
  {
    id: 9,
    slug: "elearning-platform",
    title: "E-Learning Platform",
    summary: "Online learning platform with progress tracking.",
    featured: false,
    year: 2023,
    role: "Full-stack Developer",
    stack: ["Next.js", ".NET Web API"],
    tags: ["Education", "Platform"],
    problem: "Need for a structured online learning solution.",
    solution: "Developed course modules with progress tracking.",
    result: "Improved learner engagement.",
    features: ["Course management", "Progress tracking"],
    images: ["/images/projects/elearning-1.jpg"],
    links: {},
  },
  {
    id: 10,
    slug: "task-management-app",
    title: "Task Management Application",
    summary: "A productivity app for managing tasks and priorities.",
    featured: false,
    year: 2022,
    role: "Frontend Developer",
    stack: ["React", "Next.js"],
    tags: ["Productivity"],
    problem: "Users struggled to organize daily tasks efficiently.",
    solution: "Built a clean UI with task grouping and deadlines.",
    result: "Improved task completion rates.",
    features: ["Task grouping", "Deadlines", "Responsive UI"],
    images: ["/images/projects/tasks-1.jpg"],
    links: {},
  },
  {
    id: 11,
    slug: "blog-platform",
    title: "Developer Blog Platform",
    summary: "A blogging platform focused on technical content and SEO.",
    featured: false,
    year: 2022,
    role: "Frontend Developer",
    stack: ["Next.js", "Markdown"],
    tags: ["Blog", "SEO"],
    problem: "Need for a fast and SEO-friendly blog.",
    solution: "Used static generation with markdown content.",
    result: "Fast load times and improved search visibility.",
    features: ["Markdown support", "Static generation"],
    images: ["/images/projects/blog-1.jpg"],
    links: {},
  },
  {
    id: 12,
    slug: "api-integration-service",
    title: "Third-Party API Integration Service",
    summary: "Service for integrating and aggregating multiple external APIs.",
    featured: false,
    year: 2021,
    role: "Backend Developer",
    stack: [".NET Web API"],
    tags: ["Integration", "API"],
    problem: "Multiple external APIs caused inconsistent data handling.",
    solution: "Created a unified integration layer.",
    result: "Simplified data access and reduced errors.",
    features: ["API aggregation", "Error handling"],
    images: ["/images/projects/integration-1.jpg"],
    links: {},
  },
];
